# Generated by Django 2.2 on 2019-05-14 22:00

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0003_auto_20190514_0450'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('address', models.TextField(default='', max_length=100)),
                ('city', models.CharField(default='', max_length=100)),
                ('state', models.CharField(default='', max_length=100)),
                ('zip', models.IntegerField(default=12345)),
            ],
        ),
        migrations.AddField(
            model_name='customer',
            name='type',
            field=models.CharField(choices=[(1, 'Seller'), (2, 'Vendor')], default='Customer', max_length=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customer',
            name='address',
            field=models.TextField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='customer',
            name='city',
            field=models.CharField(default='Seattle', max_length=100),
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer_id',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='customer',
            name='state',
            field=models.CharField(default='WA', max_length=100),
        ),
        migrations.AlterField(
            model_name='customer',
            name='zip',
            field=models.IntegerField(default=98105),
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('birth_date', models.DateField(default=datetime.date.today)),
                ('company_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.Company')),
                ('seller_id', models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
