# Generated by Django 2.2 on 2019-05-14 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20190514_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='type',
            field=models.CharField(choices=[(1, 'Customer'), (2, 'Vendor')], max_length=2),
        ),
    ]
