# Generated by Django 2.2 on 2019-05-14 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20190514_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='type',
            field=models.CharField(choices=[(0, 'Customer'), (1, 'Vendor')], max_length=2),
        ),
    ]
