# Generated by Django 2.2 on 2019-05-15 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20190514_1602'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seller',
            name='birth_date',
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(default='', max_length=100, unique=True),
        ),
    ]
